dataset:
  name: TropicalLeafWood
  dataset_path: ../data/leaf_wood
  train_dir: train
  val_dir: val
  test_dir: test
  # file_name: oc_016_pc.npy # Single file for prediction
  test_result_folder: ./test_pred_pointTransformer
  cache_dir: ./logs/cache_pointTransformer
  use_cache: true
  class_weights: [34512040, 9127323]
  ignored_label_inds: []
  # num_points: 40960
  # test_area_idx: 5
model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: logs/CustomPointTransformer_TropicalLeafWood_torch/checkpoint/ckpt_00300.pth # path/to/your/checkpoint
  is_resume: False
  in_channels: 3
  blocks: [2, 3, 4, 6, 3]
  num_classes: 2
  voxel_size: 0.02
  max_voxels:  50000 # 65536
  ignored_label_inds: []
  augment:
    recenter:
      dim: [0, 1, 2]
    rotate:
      method: vertical
    scale:
      min_s: 0.9 # 0.95
      max_s: 1.1 # 1.05
    noise:
      noise_std: 0.001
    # ChromaticAutoContrast:
    #   randomize_blend_factor: True
    #   blend_factor: 0.2
    # ChromaticTranslation:
    #   trans_range_ratio: 0.05
    # ChromaticJitter:
    #   std: 0.01
    # HueSaturationTranslation:
    #   hue_max: 0.5
    #   saturation_max: 0.2
pipeline:
  name: SemanticSegmentation
  device: 'cuda:0'
  optimizer:
    lr: 0.001 # 0.02
    # momentum: 0.9
    # weight_decay: 0.0001
  batch_size: 1
  # learning_rate: 0.01
  main_log_dir: logs
  max_epoch: 100
  # save_ckpt_freq: 5
  save_ckpt_best: True
  scheduler_gamma: 0.9886 # 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1