dataset:
  name: TropicalLeafWood
  dataset_path: /project/data
  train_dir: train
  val_dir: val
  test_dir: test
  # file_name: oc_016_pc.npy
  test_result_folder: ./test_pred_pointTransformer
  use_cache: true
  cache_dir: ./logs/cache_pointTransformer
  class_weights: [34512040, 9127323]
  ignored_label_inds: []
  # num_points: 40960
  # test_area_idx: 5
model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: # path/to/your/checkpoint
  is_resume: False
  in_channels: 3
  blocks: [2, 3, 4, 6, 3]
  num_classes: 2
  voxel_size: 0.02 # called grid_size in randlanet config
  max_voxels: 65536 # called num_points in randlanet config
  ignored_label_inds: []
  augment:
    recenter:
      dim: [0, 1, 2]
    rotate:
      method: vertical
    scale:
      min_s: 0.9
      max_s: 1.1
    noise:
      noise_std: 0.001
    # ChromaticAutoContrast:
    #   randomize_blend_factor: True
    #   blend_factor: 0.2
    # ChromaticTranslation:
    #   trans_range_ratio: 0.05
    # ChromaticJitter:
    #   std: 0.01
    # HueSaturationTranslation:
    #   hue_max: 0.5
    #   saturation_max: 0.2
pipeline:
  name: SemanticSegmentation
  device: 'cuda:0'
  optimizer:
    lr: 0.001 # 0.02
    # momentum: 0.9
    # weight_decay: 0.0001
  batch_size: 3
  # learning_rate: 0.01
  main_log_dir: /project/logs
  max_epoch: 300
  save_ckpt_freq: None
  save_ckpt_best: True
  scheduler_gamma: 0.9886
  test_batch_size: 1
  train_sum_dir: /project/train_log
  val_batch_size: 3
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1