dataset:
  name: TropicalLeafWood
  dataset_path: /mnt/c/Users/wavdnbro/OneDrive - UGent/Documents/spacetwin/datasets/leaf_wood/preprocessed_open3d
  train_dir: train
  val_dir: val
  test_dir: test
  cache_dir: ./logs/cache
  class_weights: [34512040, 9127323]
  ignored_label_inds: []
  num_points: 40960
  test_area_idx: 5
  test_result_folder: ./test
  use_cache: true
model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: # path/to/your/checkpoint
  in_channels: 3
  blocks: [2, 3, 4, 6, 3]
  num_classes: 2
  voxel_size: 0.04
  max_voxels: 50000
  ignored_label_inds: []
  augment:
    rotate:
      method: vertical
    scale:
      min_s: 0.95
      max_s: 1.05
    noise:
      noise_std: 0.005
    ChromaticAutoContrast:
      randomize_blend_factor: True
      blend_factor: 0.2
    ChromaticTranslation:
      trans_range_ratio: 0.05
    ChromaticJitter:
      std: 0.01
    HueSaturationTranslation:
      hue_max: 0.5
      saturation_max: 0.2
pipeline:
  name: SemanticSegmentation
  device: 'cpu'
  optimizer:
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0001
  batch_size: 3
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 512
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 3
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1