dataset:
  # name: TropicalLeafWood
  dataset_path: /mnt/c/Users/wavdnbro/OneDrive - UGent/Documents/spacetwin/datasets/leaf_wood/preprocessed_open3d # /mnt/c/Users/wavdnbro/OneDrive - UGent/Documents/spacetwin/datasets/leafon_individual_TLSdata
  test_dir: test # train
  # file_name: oc_016_pc.npy # rc_184_pc.npy
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: "logs/CustomRandLANet_TropicalLeafWood_torch/checkpoint/ckpt_00045.pth" # continue from this checkpoint (=saved weights)
  num_neighbors: 16
  num_layers: 5
  num_points: 65536 # A random sample of num_points will be taken from each point cloud as input for the model
  num_classes: 2
  class_weights: [34512040, 9127323]
  sub_sampling_ratio: [4, 4, 4, 4, 2] 
  in_channels: 3
  dim_features: 3
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.02 # Point clouds will be preprocessed with this grid size
  augment:
    recenter:
      dim: [0, 1, 2] 
pipeline:
  device: 'cuda:0'
  test_batch_size: 1
  split: test
