services:
  open3dml:
    build: .
    image: open3dml
    container_name: open3dml
    working_dir: /project
    # ports:
      # - 8050:8050 # jupyterlab
      # - 6006:6006 # tensorboard
    volumes:
      - ../cfg:/project/cfg
      - ../logs:/project/logs
      - ../scripts:/project/scripts
      - ../train_log:/project/train_log
      - /mnt/c/Users/wavdnbro/OneDrive - UGent/Documents/spacetwin/datasets/leaf_wood/preprocessed_open3d:/project/data
    # env_file: ./.env
    stdin_open: true 
    tty: true
    # restart: always
    # networks: 
    # command: /bin/bash
    ipc: host # Necessary when using multiple workers (to increase shared memory)
    # shm_size: 285340 kB
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
